### ISSUE TITLE
"power_supply ch0.pwr0 failure" but Pure1-unplugged still display "0 open alerts"

### ISSUE THREAD

**Issue by PureStrgUser01** [PureStorage-OpenConnect/pure1-unplugged#17]
Hi,
On my FA/m50 bay, one power supply is broken...
But Pure1-unplugged is still displaying "0 open alerts" on "Arrays" tab (and turning tile of my array with "i" button).
On "Messages" tab, I can see nothing but closed messages.
It looks like a bug... Thanks for help.
Best regards.

**Comment by tiberiuvs** [comment]
Hi, can you confirm that the REST API of from this array is also returning this alert?

We also previously fixed an issue regarding FlashArray alert collection (here: https://github.com/PureStorage-OpenConnect/pure1-unplugged/issues/5), and will be making an upgraded version of Pure1 Unplugged soon.

**Comment by PureStrgUser01** [comment]
Hi,
Unfortunatelly ( or the reverse :-) ), my power supply is working once again.
So I can't confirm the REST API behavior.
Regards.

**Comment by PureStrgUser01** [comment]
I have made a new install with Pure1-unplugged v1.0.2. It's fine now.
The issue is not relevant any more. I close this issue.
