### ISSUE TITLE
metricRetentionPeriod changed from 31 to 365, but still 31 days only

### ISSUE THREAD

**Issue by PureStrgUser01** [PureStorage-OpenConnect/pure1-unplugged#33]
Hi,
When I installed pure1-unplugged v1.0.0 last year, I changed metricRetentionPeriod from 31 (default) to 365 in /etc/pure1-unplugged/config.yaml configuration file.

Dashboards still display values on 31 days max, even if I request 2 months or more. It looks like 31 days max are stored.

Is it an issue or have I done something wrong ?

Best regards.

**Comment by rmaniar27** [comment]
You will need to go kibana configuration in UI to change to 365 days.

**Comment by PureStrgUser01** [comment]
That's right. You can close this issue. Thank you.
