### ISSUE TITLE
Error while upgrading pure1-unplugged v1.0.0 to v1.0.1

### ISSUE THREAD

**Issue by PureStrgUser01** [PureStorage-OpenConnect/pure1-unplugged#34]
Hi,
I want to upgrade pure1-unplugged v1.0.0 to v1.0.1. So, I did as expected in "_Pure1-Unplugged-Installation-v1.0.1-June-15-2020.pdf_":
`$ /bin/puctl --version`
`puctl version 'v1.0.1-7d4c7826'` (remplaced binary with new version)
`$ mount /dev/sr0 /mnt/cdrom`
`$ puctl upgrade mount-iso /dev/sr0` (worked fine)
`$ puctl upgrade yum-upgrade`
**ERROR: Couldn't find package pure1-unplugged.x86_64 in list of available packages**
If I try to go further:
`$ puctl pure1-unplugged upgrade` (worked fine !)

But I have:
```
$ puctl pure1-unplugged version
Pure1 Unplugged Available Version: 'v1.0.1-7d4c7826'
Pure1 Unplugged Running Version: 'v1.0.0'
```

A reboot didn't solve the issue: I'm still in v1.0.0.
What can I do to upgrade to v1.0.1 ?

Best regards.

**Comment by rmaniar27** [comment]
Hi, We would look into and get back to you

**Comment by rmaniar27** [comment]
Assuming you see the directory /media/Pure1-Unplugged_x86_64, they can run puctl infra repo enable-pure1-unplugged, and then try puctl upgrade yum-upgrade

**Comment by PureStrgUser01** [comment]
Hello,
On August 2020, I have destroyed my old VM v1.0.0, and I have installed a new VM with v1.0.1 from scratch. So I can't try this anymore.
Let's close this issue.
Nevertheless, thank you.
